# Generated by Django 5.1.6 on 2025-04-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("street_number", models.TextField()),
                ("street_name", models.TextField()),
                ("apartment_number", models.TextField(blank=True)),
                ("zip_code", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                ("date_of_registration", models.DateField()),
                ("party", models.CharField(max_length=2)),
                ("precinct", models.CharField(max_length=10)),
                ("v20state", models.CharField(max_length=1)),
                ("v21town", models.CharField(max_length=1)),
                ("v21primary", models.CharField(max_length=1)),
                ("v22general", models.CharField(max_length=1)),
                ("v23town", models.CharField(max_length=1)),
                ("voter_score", models.IntegerField()),
            ],
        ),
    ]
