# Generated by Django 5.1.6 on 2025-04-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_customer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
