# Generated by Django 5.1.6 on 2025-04-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_appointment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nailtechnician",
            name="availability_notes",
        ),
        migrations.RemoveField(
            model_name="nailtechnician",
            name="specialties",
        ),
    ]
